In [21]:
import pandas
import numpy
from matplotlib import pyplot
import seaborn

from PIL import Image

In [22]:
catdogs = pandas.read_csv("catdogs.csv")

catdogs

          ID TYPE                         PATH        ORIGINAL_PATH
0          0  Cat      ../../catdogs/Cat_0.png      ../../Cat/0.jpg
1          1  Cat      ../../catdogs/Cat_1.png      ../../Cat/1.jpg
2          2  Cat      ../../catdogs/Cat_2.png      ../../Cat/2.jpg
3          3  Cat      ../../catdogs/Cat_3.png      ../../Cat/3.jpg
4          4  Cat      ../../catdogs/Cat_4.png      ../../Cat/4.jpg
...      ...  ...                          ...                  ...
24993  12495  Dog  ../../catdogs/Dog_12495.png  ../../Dog/12495.jpg
24994  12496  Dog  ../../catdogs/Dog_12496.png  ../../Dog/12496.jpg
24995  12497  Dog  ../../catdogs/Dog_12497.png  ../../Dog/12497.jpg
24996  12498  Dog  ../../catdogs/Dog_12498.png  ../../Dog/12498.jpg
24997  12499  Dog  ../../catdogs/Dog_12499.png  ../../Dog/12499.jpg

[24998 rows x 4 columns]

In [23]:
catdogs["PATH"]

0            ../../catdogs/Cat_0.png
1            ../../catdogs/Cat_1.png
2            ../../catdogs/Cat_2.png
3            ../../catdogs/Cat_3.png
4            ../../catdogs/Cat_4.png
                    ...
24993    ../../catdogs/Dog_12495.png
24994    ../../catdogs/Dog_12496.png
24995    ../../catdogs/Dog_12497.png
24996    ../../catdogs/Dog_12498.png
24997    ../../catdogs/Dog_12499.png
Name: PATH, Length: 24998, dtype: object

In [39]:
X = numpy.vstack(
    catdogs["PATH"].apply(
        lambda path: numpy.ascontiguousarray(Image.open(path).convert("L")).reshape(64 * 64))
        .apply(lambda x: (255 - x) / 255).values)

X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
catdogs["TYPE"]

0        Cat
1        Cat
2        Cat
3        Cat
4        Cat
        ...
24993    Dog
24994    Dog
24995    Dog
24996    Dog
24997    Dog
Name: TYPE, Length: 24998, dtype: object

In [41]:
y1 = (catdogs["TYPE"] == "Cat").astype(int)
y2 = (catdogs["TYPE"] == "Dog").astype(int)

Y = pandas.DataFrame({
    "y1": y1,
    "y2": y2,
})

Y

       y1  y2
0       1   0
1       1   0
2       1   0
3       1   0
4       1   0
...    ..  ..
24993   0   1
24994   0   1
24995   0   1
24996   0   1
24997   0   1

[24998 rows x 2 columns]

In [42]:
! pip install scikit-learn

WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)
Requirement already satisfied: scikit-learn in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
from sklearn.model_selection import train_test_split

Xa, Xb, Ya, Yb = train_test_split(X, Y, test_size=3000, random_state=123)

In [44]:
Xa

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.49803922, 0.54901961, 0.53333333, ..., 0.38039216, 0.38431373,
        0.3372549 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [45]:
import keras

modelo = keras.Sequential([
    keras.Input(shape=(64 * 64,)),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │       524,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 541,186 (2.06 MB)

 Trainable params: 541,186 (2.06 MB)

 Non-trainable params: 0 (0.00 B)

In [46]:
modelo.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [48]:
historial = modelo.fit(Xa, Ya, epochs=100)

Epoch 1/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6086 - loss: 0.6601
Epoch 2/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6060 - loss: 0.6600
Epoch 3/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6061 - loss: 0.6574
Epoch 4/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6097 - loss: 0.6558
Epoch 5/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6182 - loss: 0.6501
Epoch 6/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6251 - loss: 0.6469
Epoch 7/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6219 - loss: 0.6474
Epoch 8/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6324 - loss: 0.6419
Epoch 9/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6305 - loss: 0.6402
Epoch 10/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6311 - loss: 0.6428
Epoch 11/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6313 - loss: 0.6403
Epoch 12/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6392 - loss: 0.6340
Epoch 13/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6329 - loss: 0.6399
Epoch 14/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6413 - loss: 0.6343
Epoch 15/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6458 - loss: 0.6323
Epoch 16/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6469 - loss: 0.6301
Epoch 17/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6390 - loss: 0.6307
Epoch 18/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6425 - loss: 0.6271
Epoch 19/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6491 - loss: 0.6252
Epoch 20/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6524 - loss: 0.6238
Epoch 21/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6452 - loss: 0.6250
Epoch 22/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6496 - loss: 0.6227
Epoch 23/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6521 - loss: 0.6189
Epoch 24/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6578 - loss: 0.6157
Epoch 25/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6541 - loss: 0.6151
Epoch 26/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6503 - loss: 0.6176
Epoch 27/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6638 - loss: 0.6086
Epoch 28/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6639 - loss: 0.6086
Epoch 29/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6676 - loss: 0.6058
Epoch 30/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6631 - loss: 0.6098
Epoch 31/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6597 - loss: 0.6102
Epoch 32/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6642 - loss: 0.6066
Epoch 33/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6708 - loss: 0.5995
Epoch 34/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6724 - loss: 0.6023
Epoch 35/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6671 - loss: 0.6022
Epoch 36/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6668 - loss: 0.6010
Epoch 37/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6742 - loss: 0.5966
Epoch 38/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6731 - loss: 0.5967
Epoch 39/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6722 - loss: 0.5993
Epoch 40/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6692 - loss: 0.6016
Epoch 41/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6754 - loss: 0.5949
Epoch 42/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6731 - loss: 0.5933
Epoch 43/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6750 - loss: 0.5925
Epoch 44/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6687 - loss: 0.5980
Epoch 45/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6784 - loss: 0.5856
Epoch 46/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6790 - loss: 0.5906
Epoch 47/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6764 - loss: 0.5919
Epoch 48/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6857 - loss: 0.5865
Epoch 49/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6933 - loss: 0.5811
Epoch 50/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6877 - loss: 0.5815
Epoch 51/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6783 - loss: 0.5889
Epoch 52/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6870 - loss: 0.5833
Epoch 53/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6847 - loss: 0.5825
Epoch 54/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6820 - loss: 0.5858
Epoch 55/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6960 - loss: 0.5724
Epoch 56/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6895 - loss: 0.5751
Epoch 57/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6928 - loss: 0.5761
Epoch 58/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6947 - loss: 0.5764
Epoch 59/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6873 - loss: 0.5771
Epoch 60/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6931 - loss: 0.5740
Epoch 61/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6981 - loss: 0.5685
Epoch 62/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6975 - loss: 0.5639
Epoch 63/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6884 - loss: 0.5812
Epoch 64/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7027 - loss: 0.5659
Epoch 65/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6939 - loss: 0.5684
Epoch 66/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7005 - loss: 0.5654
Epoch 67/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6962 - loss: 0.5696
Epoch 68/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6979 - loss: 0.5700
Epoch 69/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6946 - loss: 0.5681
Epoch 70/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7091 - loss: 0.5593
Epoch 71/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7101 - loss: 0.5571
Epoch 72/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7054 - loss: 0.5627
Epoch 73/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7037 - loss: 0.5602
Epoch 74/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7056 - loss: 0.5593
Epoch 75/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7053 - loss: 0.5602
Epoch 76/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6995 - loss: 0.5595
Epoch 77/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7030 - loss: 0.5594
Epoch 78/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7048 - loss: 0.5567
Epoch 79/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7082 - loss: 0.5596
Epoch 80/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7142 - loss: 0.5519
Epoch 81/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7060 - loss: 0.5557
Epoch 82/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7087 - loss: 0.5524
Epoch 83/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7110 - loss: 0.5542
Epoch 84/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7202 - loss: 0.5420
Epoch 85/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7160 - loss: 0.5499
Epoch 86/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7156 - loss: 0.5474
Epoch 87/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7215 - loss: 0.5417
Epoch 88/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7239 - loss: 0.5349
Epoch 89/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7192 - loss: 0.5385
Epoch 90/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7127 - loss: 0.5458
Epoch 91/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7166 - loss: 0.5459
Epoch 92/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7175 - loss: 0.5443
Epoch 93/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7204 - loss: 0.5443
Epoch 94/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7251 - loss: 0.5351
Epoch 95/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7242 - loss: 0.5357
Epoch 96/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7229 - loss: 0.5342
Epoch 97/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7264 - loss: 0.5338
Epoch 98/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7138 - loss: 0.5443
Epoch 99/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7266 - loss: 0.5334
Epoch 100/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7270 - loss: 0.5278

In [49]:
modelo.evaluate(Xb, Yb)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.5971 - loss: 0.7787

[0.7850287556648254, 0.5929999947547913]